import type { Receta } from '../dominio/tipos'

/**
 * Recetario base, todo dentro del protocolo (con huevo y trigo sarraceno,
 * que Cami ya tiene reintroducidos).
 *
 * Cada ingrediente puede declarar `alternativas`: reemplazos que funcionan
 * EN ESTA receta. La app los usa para dos cosas: dar por cubierto un
 * ingrediente que no tenés pero podés reemplazar, y sugerirte el cambio
 * cuando algo no se consigue.
 */
export const RECETAS: Receta[] = [
  // ══════════════════════ DESAYUNOS ══════════════════════
  {
    id: 'panqueques-sarraceno',
    nombre: 'Panqueques de sarraceno y banana',
    emoji: '🥞',
    descripcion: 'Los panqueques de todos los días: salen finitos, se doblan bien y aguantan dulce o salado.',
    momentos: ['desayuno', 'dulce', 'merienda'],
    porciones: 2,
    minutos: 20,
    ingredientes: [
      { id: 'harina-sarraceno', cantidad: '1 taza', alternativas: ['harina-mandioca', 'harina-platano'], nota: 'con harina de mandioca la masa pide un poco menos de líquido' },
      { id: 'huevo', cantidad: '2' },
      { id: 'banana', cantidad: '1 madura' },
      { id: 'leche-coco', cantidad: '3/4 taza', alternativas: ['agua-coco', 'agua'] },
      { id: 'canela', cantidad: '1 cdita', opcional: true },
      { id: 'sal', cantidad: '1 pizca' },
      { id: 'aceite-coco', cantidad: 'para la sartén', alternativas: ['grasa-cerdo', 'aceite-oliva'] },
    ],
    pasos: [
      'Pisá la banana con un tenedor hasta que quede sin grumos grandes.',
      'Agregá los huevos y la leche de coco, y mezclá bien.',
      'Sumá la harina, la canela y la sal. Batí hasta que quede una masa lisa y dejala reposar 5 minutos: espesa sola.',
      'Calentá una sartén con un toque de aceite de coco a fuego medio.',
      'Echá un cucharón chico, cociná 2 minutos hasta que aparezcan burbujas en la superficie, dalo vuelta y hacelo 1 minuto más.',
      'Repetí con el resto, engrasando la sartén entre panqueque y panqueque.',
    ],
    nota: 'Si los querés salados, sacá la banana y la canela y sumá ciboulette picado.',
  },
  {
    id: 'revuelto-espinaca-hongos',
    nombre: 'Revuelto de huevo con espinaca y champiñones',
    emoji: '🍳',
    descripcion: 'Desayuno salado de 10 minutos, con verdura adentro desde temprano.',
    momentos: ['desayuno', 'cena'],
    porciones: 2,
    minutos: 12,
    ingredientes: [
      { id: 'huevo', cantidad: '4' },
      { id: 'espinaca', cantidad: '2 puñados', alternativas: ['acelga', 'kale', 'rucula'] },
      { id: 'champinon', cantidad: '150 g' },
      { id: 'cebolla-verdeo', cantidad: '1', alternativas: ['ciboulette', 'puerro', 'cebolla'] },
      { id: 'aceite-oliva', cantidad: '1 cda', alternativas: ['aceite-coco', 'grasa-cerdo'] },
      { id: 'sal', cantidad: 'a gusto' },
      { id: 'curcuma', cantidad: '1 pizca', opcional: true },
    ],
    pasos: [
      'Cortá los champiñones en láminas y la cebolla de verdeo en aros finos.',
      'Salteá los champiñones en el aceite a fuego fuerte, sin moverlos mucho, hasta que se doren (4 minutos).',
      'Agregá la cebolla de verdeo y la espinaca, y cociná hasta que la hoja se achique.',
      'Bajá el fuego, volcá los huevos batidos con sal y revolvé suave hasta que cuajen pero queden cremosos.',
    ],
  },
  {
    id: 'porridge-coco-manzana',
    nombre: 'Porridge de coco y manzana',
    emoji: '🥣',
    descripcion: 'La versión sin avena del desayuno caliente. Cremoso y dulce sin azúcar agregada.',
    momentos: ['desayuno', 'merienda'],
    porciones: 2,
    minutos: 15,
    ingredientes: [
      { id: 'harina-coco', cantidad: '4 cdas', alternativas: ['coco-rallado'] },
      { id: 'leche-coco', cantidad: '1 taza', alternativas: ['agua-coco'] },
      { id: 'manzana', cantidad: '1', alternativas: ['pera', 'banana'] },
      { id: 'canela', cantidad: '1 cdita' },
      { id: 'miel', cantidad: '1 cdita', opcional: true, alternativas: ['jarabe-arce'] },
      { id: 'arandano', cantidad: 'un puñado', opcional: true, alternativas: ['frutilla', 'frambuesa'] },
    ],
    pasos: [
      'Rallá la manzana con cáscara.',
      'Llevá la leche de coco a fuego bajo con la manzana y la canela, 5 minutos.',
      'Agregá la harina de coco de a poco, revolviendo, hasta que espese a gusto.',
      'Sacá del fuego, dejá reposar 2 minutos (sigue espesando) y serví con la fruta arriba.',
    ],
  },
  {
    id: 'tortilla-zapallito',
    nombre: 'Tortilla de zapallito y cebolla de verdeo',
    emoji: '🧆',
    descripcion: 'Rinde frío y caliente. Sirve de desayuno, de vianda o de cena liviana.',
    momentos: ['desayuno', 'almuerzo', 'cena'],
    porciones: 4,
    minutos: 30,
    ingredientes: [
      { id: 'zapallito', cantidad: '3 medianos', alternativas: ['zanahoria', 'zapallo'] },
      { id: 'huevo', cantidad: '5' },
      { id: 'cebolla-verdeo', cantidad: '2', alternativas: ['cebolla', 'puerro'] },
      { id: 'ajo', cantidad: '1 diente' },
      { id: 'perejil', cantidad: '2 cdas', alternativas: ['albahaca', 'ciboulette'] },
      { id: 'aceite-oliva', cantidad: '2 cdas' },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Rallá los zapallitos grueso, salalos y dejalos 10 minutos en un colador. Apretalos para sacarles el agua: este paso decide si la tortilla queda firme o aguada.',
      'Salteá la cebolla de verdeo y el ajo picados en el aceite, 3 minutos.',
      'Sumá el zapallito escurrido y cociná 5 minutos más.',
      'Mezclá con los huevos batidos, el perejil y sal.',
      'Volcá en la sartén a fuego bajo, tapá y cociná 8 minutos. Dala vuelta con la ayuda de un plato y hacela 4 minutos del otro lado.',
    ],
  },

  // ══════════════════════ PLATOS PRINCIPALES ══════════════════════
  {
    id: 'pollo-batatas-romero',
    nombre: 'Pollo al horno con batatas y romero',
    emoji: '🍗',
    descripcion: 'Una asadera, todo junto al horno. El plato de cabecera cuando no hay tiempo ni ganas.',
    momentos: ['almuerzo', 'cena'],
    porciones: 4,
    minutos: 55,
    ingredientes: [
      { id: 'muslo-pollo', cantidad: '6', alternativas: ['pechuga-pollo', 'pollo'] },
      { id: 'batata', cantidad: '2 grandes', alternativas: ['mandioca', 'zapallo', 'zanahoria'], nota: 'la mandioca tarda un poco más: cortala más chica' },
      { id: 'cebolla', cantidad: '2', alternativas: ['puerro'] },
      { id: 'ajo', cantidad: '4 dientes' },
      { id: 'romero', cantidad: '2 ramas', alternativas: ['tomillo', 'salvia', 'oregano'] },
      { id: 'aceite-oliva', cantidad: '3 cdas', alternativas: ['grasa-cerdo', 'aceite-palta'] },
      { id: 'limon', cantidad: '1' },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Precalentá el horno a 200 °C.',
      'Cortá las batatas en gajos gruesos y las cebollas en cuartos. Ponelos en una asadera con el ajo entero.',
      'Rociá con aceite, sal y el romero. Mezclá con las manos para que se impregne todo.',
      'Apoyá los muslos arriba, con la piel para arriba, y salalos.',
      'Horneá 45 minutos, hasta que la piel esté dorada y la batata tierna.',
      'Sacá del horno y exprimí el limón por encima antes de servir.',
    ],
  },
  {
    id: 'salmon-esparragos',
    nombre: 'Salmón al horno con espárragos y limón',
    emoji: '🐟',
    descripcion: 'Veinte minutos de principio a fin y una sola fuente para lavar.',
    momentos: ['almuerzo', 'cena'],
    porciones: 2,
    minutos: 20,
    ingredientes: [
      { id: 'salmon', cantidad: '2 filetes', alternativas: ['trucha', 'merluza', 'caballa'] },
      { id: 'esparrago', cantidad: '1 atado', alternativas: ['chaucha', 'brocoli', 'zapallito'] },
      { id: 'limon', cantidad: '1', alternativas: ['lima'] },
      { id: 'aceite-oliva', cantidad: '2 cdas' },
      { id: 'eneldo', cantidad: '1 cda', opcional: true, alternativas: ['perejil', 'ciboulette'] },
      { id: 'ajo', cantidad: '1 diente' },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Precalentá el horno a 200 °C.',
      'Acomodá los espárragos en una fuente, rociados con aceite, ajo picado y sal.',
      'Apoyá los filetes de salmón encima, con sal y rodajas de limón arriba.',
      'Horneá 12 a 14 minutos: el salmón está listo cuando se separa en láminas al apoyar un tenedor.',
      'Terminá con eneldo fresco y un chorrito de limón.',
    ],
  },
  {
    id: 'salteado-carne-brocoli',
    nombre: 'Salteado de carne con brócoli y jengibre',
    emoji: '🥦',
    descripcion: 'El wok de la semana, sin salsa de soja pero con todo el sabor.',
    momentos: ['almuerzo', 'cena'],
    porciones: 3,
    minutos: 25,
    ingredientes: [
      { id: 'carne-vacuna', cantidad: '500 g en tiras', alternativas: ['pechuga-pollo', 'cerdo', 'pavo'] },
      { id: 'brocoli', cantidad: '1', alternativas: ['coliflor', 'repollo', 'chaucha'] },
      { id: 'zanahoria', cantidad: '2' },
      { id: 'cebolla-verdeo', cantidad: '3', alternativas: ['cebolla', 'puerro'] },
      { id: 'jengibre', cantidad: '1 cda rallado' },
      { id: 'ajo', cantidad: '3 dientes' },
      { id: 'vinagre-coco', cantidad: '2 cdas', alternativas: ['vinagre-manzana', 'limon'] },
      { id: 'aceite-coco', cantidad: '2 cdas', alternativas: ['aceite-palta', 'grasa-cerdo'] },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Cortá la carne en tiras finas contra la fibra y salala.',
      'Cortá el brócoli en ramitos chicos y la zanahoria en bastones finos.',
      'Calentá bien el wok o la sartén más grande que tengas. Sellá la carne en dos tandas, 2 minutos cada una, y reservala.',
      'En la misma sartén salteá zanahoria y brócoli 4 minutos, con un chorrito de agua para que se hagan al vapor.',
      'Sumá ajo, jengibre y cebolla de verdeo, 1 minuto.',
      'Volvé a poner la carne, agregá el vinagre, mezclá 30 segundos y servilo enseguida.',
    ],
  },
  {
    id: 'guiso-pollo-zapallo',
    nombre: 'Guiso de pollo con zapallo y zanahoria',
    emoji: '🍲',
    descripcion: 'Olla grande, comida para dos días. Levanta mejor al día siguiente.',
    momentos: ['almuerzo', 'cena'],
    porciones: 5,
    minutos: 60,
    ingredientes: [
      { id: 'muslo-pollo', cantidad: '6', alternativas: ['pollo', 'pechuga-pollo'] },
      { id: 'zapallo', cantidad: '600 g', alternativas: ['batata', 'zanahoria', 'mandioca'] },
      { id: 'zanahoria', cantidad: '3' },
      { id: 'apio', cantidad: '2 tallos', alternativas: ['hinojo', 'puerro'] },
      { id: 'cebolla', cantidad: '2' },
      { id: 'ajo', cantidad: '4 dientes' },
      { id: 'caldo-huesos', cantidad: '1 litro', alternativas: ['caldo-verduras', 'agua'] },
      { id: 'laurel', cantidad: '2 hojas' },
      { id: 'tomillo', cantidad: '1 cdita', alternativas: ['romero', 'oregano'] },
      { id: 'aceite-oliva', cantidad: '2 cdas' },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Dorá los muslos en la olla con el aceite, de los dos lados, y reservalos.',
      'En la misma grasa, rehogá cebolla, apio y zanahoria picados, 8 minutos.',
      'Sumá el ajo, el laurel y el tomillo, 1 minuto más.',
      'Volvé a poner el pollo, cubrí con el caldo y llevá a hervor suave.',
      'Cociná tapado 25 minutos. Agregá el zapallo en cubos y seguí 20 minutos más, hasta que esté tierno.',
      'Corregí la sal. Si lo querés más espeso, pisá un par de trozos de zapallo dentro de la olla.',
    ],
  },
  {
    id: 'albondigas-pure-coliflor',
    nombre: 'Albóndigas con puré de coliflor',
    emoji: '🍛',
    descripcion: 'Comfort food del protocolo: albóndigas jugosas sobre un puré bien cremoso.',
    momentos: ['almuerzo', 'cena'],
    porciones: 4,
    minutos: 45,
    ingredientes: [
      { id: 'carne-picada', cantidad: '600 g', alternativas: ['cordero', 'cerdo', 'pavo'] },
      { id: 'coliflor', cantidad: '1 grande', alternativas: ['zapallo', 'batata', 'nabo', 'mandioca'], nota: 'con zapallo o batata el puré sale más dulce y más denso' },
      { id: 'cebolla', cantidad: '1' },
      { id: 'ajo', cantidad: '3 dientes' },
      { id: 'perejil', cantidad: '3 cdas', alternativas: ['albahaca', 'cilantro'] },
      { id: 'harina-mandioca', cantidad: '2 cdas', alternativas: ['almidon-mandioca', 'harina-coco'], nota: 'liga la albóndiga; con harina de coco usá la mitad' },
      { id: 'leche-coco', cantidad: '1/2 taza', alternativas: ['crema-coco', 'caldo-huesos'] },
      { id: 'aceite-oliva', cantidad: '2 cdas' },
      { id: 'oregano', cantidad: '1 cdita', alternativas: ['tomillo', 'albahaca'] },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Mezclá la carne con la cebolla rallada, el ajo picado, el perejil, el orégano, la harina de mandioca y sal. Amasá poco: si la trabajás de más quedan duras.',
      'Formá albóndigas del tamaño de una nuez y dejalas 10 minutos en la heladera.',
      'Hervé la coliflor en ramitos hasta que esté muy tierna (12 minutos) y escurrila bien.',
      'Procesá la coliflor con la leche de coco y sal hasta que quede un puré liso.',
      'Dorá las albóndigas en la sartén con aceite, girándolas, 10 minutos en total.',
      'Serví las albóndigas sobre el puré, con el jugo de la sartén por encima.',
    ],
  },
  {
    id: 'merluza-hinojo-naranja',
    nombre: 'Merluza con ensalada de hinojo y naranja',
    emoji: '🍊',
    descripcion: 'Liviana y fresca. El hinojo crudo con naranja levanta cualquier pescado blanco.',
    momentos: ['almuerzo', 'cena'],
    porciones: 2,
    minutos: 20,
    ingredientes: [
      { id: 'merluza', cantidad: '2 filetes', alternativas: ['trucha', 'salmon'] },
      { id: 'hinojo', cantidad: '1 bulbo', alternativas: ['apio', 'pepino', 'rabanito'] },
      { id: 'naranja', cantidad: '1', alternativas: ['mandarina', 'pomelo'] },
      { id: 'rucula', cantidad: '1 puñado', alternativas: ['berro', 'lechuga', 'radicheta'] },
      { id: 'aceite-oliva', cantidad: '3 cdas' },
      { id: 'limon', cantidad: '1/2' },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Cortá el hinojo en láminas lo más finas que puedas y dejalo 5 minutos en agua fría con hielo: queda crocante.',
      'Pelá la naranja a vivo y sacá los gajos, guardando el jugo que suelte.',
      'Mezclá hinojo escurrido, naranja y rúcula con aceite, el jugo de naranja y sal.',
      'Salá los filetes y cocinalos en sartén bien caliente con aceite, 3 minutos de cada lado.',
      'Serví el pescado con la ensalada al lado y limón exprimido encima.',
    ],
  },
  {
    id: 'wok-camarones-repollo',
    nombre: 'Wok de camarones con repollo y jengibre',
    emoji: '🦐',
    descripcion: 'Quince minutos reales. De la heladera a la mesa sin escalas.',
    momentos: ['almuerzo', 'cena'],
    porciones: 2,
    minutos: 15,
    ingredientes: [
      { id: 'camaron', cantidad: '400 g', alternativas: ['calamar', 'mejillon', 'pechuga-pollo'] },
      { id: 'repollo', cantidad: '1/2', alternativas: ['repollo-colorado', 'kale', 'brocoli'] },
      { id: 'zanahoria', cantidad: '1' },
      { id: 'jengibre', cantidad: '1 cda rallado' },
      { id: 'ajo', cantidad: '2 dientes' },
      { id: 'cilantro', cantidad: '3 cdas', opcional: true, alternativas: ['perejil', 'ciboulette'] },
      { id: 'lima', cantidad: '1', alternativas: ['limon'] },
      { id: 'aceite-coco', cantidad: '2 cdas', alternativas: ['aceite-palta'] },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Cortá el repollo en tiras finas y la zanahoria en bastones.',
      'Calentá el aceite a fuego fuerte y salteá los camarones 2 minutos, hasta que se pongan opacos. Sacalos.',
      'Tirá el repollo y la zanahoria al wok, 4 minutos, moviendo.',
      'Sumá ajo y jengibre, 1 minuto.',
      'Devolvé los camarones, salá, apagá el fuego y terminá con cilantro y jugo de lima.',
    ],
  },
  {
    id: 'zapallitos-rellenos',
    nombre: 'Zapallitos rellenos de carne',
    emoji: '🥒',
    descripcion: 'Plato de domingo. Se arman antes y van al horno cuando hace falta.',
    momentos: ['almuerzo', 'cena'],
    porciones: 4,
    minutos: 60,
    ingredientes: [
      { id: 'zapallito', cantidad: '6 redondos', alternativas: ['zapallo'], nota: 'si usás zapallo, cortalo en mitades y ahuecalo' },
      { id: 'carne-picada', cantidad: '500 g', alternativas: ['pavo', 'cordero'] },
      { id: 'cebolla', cantidad: '1' },
      { id: 'ajo', cantidad: '2 dientes' },
      { id: 'zanahoria', cantidad: '1' },
      { id: 'huevo', cantidad: '1' },
      { id: 'perejil', cantidad: '3 cdas', alternativas: ['albahaca'] },
      { id: 'oregano', cantidad: '1 cdita' },
      { id: 'aceite-oliva', cantidad: '2 cdas' },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Hervé los zapallitos enteros 8 minutos, hasta que estén apenas tiernos. Dejalos entibiar.',
      'Cortales la tapita y ahuecalos con una cuchara. Picá la pulpa y reservala.',
      'Salteá cebolla, ajo y zanahoria picados 6 minutos. Agregá la carne y cocinala hasta que pierda el rojo.',
      'Sumá la pulpa picada, el orégano y sal. Cociná 5 minutos y dejá entibiar.',
      'Mezclá el relleno con el huevo y el perejil, y rellená los zapallitos.',
      'Horneá a 190 °C durante 25 minutos.',
    ],
  },
  {
    id: 'sopa-zapallo-jengibre',
    nombre: 'Sopa crema de zapallo y jengibre',
    emoji: '🎃',
    descripcion: 'Sedosa sin una gota de crema. Se congela perfecto en porciones.',
    momentos: ['almuerzo', 'cena'],
    porciones: 4,
    minutos: 40,
    ingredientes: [
      { id: 'zapallo', cantidad: '1 kg', alternativas: ['batata', 'zanahoria'] },
      { id: 'cebolla', cantidad: '1', alternativas: ['puerro'] },
      { id: 'jengibre', cantidad: '2 cdas rallado' },
      { id: 'ajo', cantidad: '2 dientes' },
      { id: 'caldo-huesos', cantidad: '1 litro', alternativas: ['caldo-verduras', 'agua'] },
      { id: 'leche-coco', cantidad: '1/2 taza', alternativas: ['crema-coco'] },
      { id: 'aceite-coco', cantidad: '2 cdas', alternativas: ['aceite-oliva'] },
      { id: 'curcuma', cantidad: '1 cdita', opcional: true },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Rehogá la cebolla en el aceite hasta que esté transparente, 6 minutos.',
      'Sumá ajo, jengibre y cúrcuma, 1 minuto.',
      'Agregá el zapallo en cubos y el caldo. Hervé 25 minutos, hasta que se deshaga.',
      'Procesá hasta que quede completamente liso.',
      'Volvé al fuego, incorporá la leche de coco, corregí la sal y calentá sin que hierva.',
    ],
  },
  {
    id: 'milanesas-pollo-mandioca',
    nombre: 'Milanesas de pollo con rebozado de mandioca y coco',
    emoji: '🍖',
    descripcion: 'Crocantes de verdad, sin pan rallado. Al horno quedan mejor que fritas.',
    momentos: ['almuerzo', 'cena'],
    porciones: 4,
    minutos: 40,
    ingredientes: [
      { id: 'pechuga-pollo', cantidad: '4 filetes finos', alternativas: ['pavo', 'merluza'] },
      { id: 'harina-mandioca', cantidad: '1 taza', alternativas: ['harina-platano', 'harina-sarraceno'] },
      { id: 'coco-rallado', cantidad: '1/2 taza', alternativas: ['harina-coco'] },
      { id: 'huevo', cantidad: '2' },
      { id: 'ajo-polvo', cantidad: '1 cdita', alternativas: ['ajo'] },
      { id: 'oregano', cantidad: '1 cdita', alternativas: ['tomillo', 'romero'] },
      { id: 'aceite-oliva', cantidad: '3 cdas', alternativas: ['aceite-palta'] },
      { id: 'sal', cantidad: 'a gusto' },
      { id: 'limon', cantidad: '1', opcional: true },
    ],
    pasos: [
      'Precalentá el horno a 210 °C con la asadera adentro: el rebozado se dora desde abajo.',
      'Mezclá la harina de mandioca con el coco rallado, el ajo en polvo, el orégano y sal.',
      'Batí los huevos en un plato hondo y salá los filetes.',
      'Pasá cada filete por huevo y después por la mezcla seca, apretando bien para que se pegue.',
      'Sacá la asadera caliente, rociala con aceite, apoyá las milanesas y rociá por encima.',
      'Horneá 15 minutos, dalas vuelta y hacé 10 minutos más. Serví con limón.',
    ],
  },
  {
    id: 'pollo-coco-curcuma',
    nombre: 'Pollo al coco con cúrcuma y jengibre',
    emoji: '🥥',
    descripcion: 'El sabor de un curry sin usar curry: la mezcla comercial tiene semillas y ají.',
    momentos: ['almuerzo', 'cena'],
    porciones: 4,
    minutos: 40,
    ingredientes: [
      { id: 'muslo-pollo', cantidad: '6 sin hueso', alternativas: ['pechuga-pollo', 'camaron'] },
      { id: 'leche-coco', cantidad: '400 ml' },
      { id: 'cebolla', cantidad: '2' },
      { id: 'ajo', cantidad: '4 dientes' },
      { id: 'jengibre', cantidad: '2 cdas rallado' },
      { id: 'curcuma', cantidad: '1 cda' },
      { id: 'zanahoria', cantidad: '2', alternativas: ['zapallo', 'batata', 'chaucha'] },
      { id: 'espinaca', cantidad: '2 puñados', opcional: true, alternativas: ['acelga', 'kale'] },
      { id: 'lima', cantidad: '1', alternativas: ['limon'] },
      { id: 'cilantro', cantidad: '3 cdas', opcional: true, alternativas: ['perejil'] },
      { id: 'aceite-coco', cantidad: '2 cdas' },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Cortá el pollo en trozos grandes y salalo.',
      'Rehogá la cebolla en el aceite de coco 8 minutos, hasta que esté bien blanda y dulce.',
      'Sumá ajo, jengibre y cúrcuma y cociná 1 minuto, hasta que largue el aroma.',
      'Agregá el pollo y sellalo por fuera, 5 minutos.',
      'Volcá la leche de coco y la zanahoria en rodajas. Cociná a fuego bajo 20 minutos, sin tapa, hasta que la salsa espese.',
      'Apagá, sumá la espinaca (se cocina con el calor residual), el jugo de lima y el cilantro.',
    ],
  },
  {
    id: 'hamburguesas-palta-chucrut',
    nombre: 'Hamburguesas con palta y chucrut',
    emoji: '🍔',
    descripcion: 'Sin pan y sin extrañarlo: el chucrut hace el trabajo que hacía el pickle.',
    momentos: ['almuerzo', 'cena'],
    porciones: 4,
    minutos: 25,
    ingredientes: [
      { id: 'carne-picada', cantidad: '600 g', alternativas: ['cordero', 'pavo'] },
      { id: 'cebolla', cantidad: '1' },
      { id: 'ajo', cantidad: '2 dientes' },
      { id: 'harina-mandioca', cantidad: '1 cda', alternativas: ['almidon-mandioca'] },
      { id: 'palta', cantidad: '2' },
      { id: 'chucrut', cantidad: '4 cdas', alternativas: ['rabanito', 'pepino'] },
      { id: 'lechuga', cantidad: '8 hojas grandes', alternativas: ['repollo'], nota: 'las hojas hacen de pan' },
      { id: 'aceite-oliva', cantidad: '1 cda' },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Mezclá la carne con cebolla rallada, ajo picado, la harina de mandioca y sal.',
      'Armá 4 medallones y hundí el centro con el pulgar para que no se inflen al cocinarse.',
      'Cocinalos en sartén bien caliente con aceite, 4 minutos de cada lado.',
      'Pisá la palta con sal y un poco de limón.',
      'Armá cada hamburguesa entre dos hojas de lechuga, con palta y chucrut arriba.',
    ],
  },
  {
    id: 'estofado-carne-nabos',
    nombre: 'Estofado de carne con nabos y laurel',
    emoji: '🥘',
    descripcion: 'Cocción larga y poco trabajo. Es la receta para un domingo de frío.',
    momentos: ['almuerzo', 'cena'],
    porciones: 5,
    minutos: 150,
    ingredientes: [
      { id: 'carne-vacuna', cantidad: '1 kg (roast beef o paleta)', alternativas: ['cordero', 'cerdo'] },
      { id: 'nabo', cantidad: '4', alternativas: ['zanahoria', 'mandioca', 'batata'] },
      { id: 'zanahoria', cantidad: '3' },
      { id: 'cebolla', cantidad: '2' },
      { id: 'puerro', cantidad: '1', alternativas: ['cebolla-verdeo', 'apio'] },
      { id: 'ajo', cantidad: '5 dientes' },
      { id: 'caldo-huesos', cantidad: '750 ml', alternativas: ['caldo-verduras', 'agua'] },
      { id: 'laurel', cantidad: '3 hojas' },
      { id: 'romero', cantidad: '1 rama', alternativas: ['tomillo'] },
      { id: 'grasa-cerdo', cantidad: '2 cdas', alternativas: ['aceite-oliva', 'grasa-pato'] },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Cortá la carne en trozos grandes, secalos bien con papel y salalos.',
      'Sellalos en la olla con la grasa, por tandas, hasta que estén bien dorados. No amontones la carne.',
      'Reservá la carne y rehogá cebolla, puerro y ajo en el mismo fondo, 8 minutos.',
      'Volvé a poner la carne, sumá el caldo, el laurel y el romero. Tapá y cociná a fuego mínimo 1 hora y media.',
      'Agregá nabos y zanahorias en trozos, y seguí 40 minutos más, destapado, hasta que la salsa espese.',
      'Corregí la sal y dejalo reposar 10 minutos antes de servir.',
    ],
  },
  {
    id: 'higado-encebollado',
    nombre: 'Hígado encebollado',
    emoji: '🧅',
    descripcion: 'El alimento más denso en nutrientes del protocolo. La clave es no pasarlo de cocción.',
    momentos: ['almuerzo', 'cena'],
    porciones: 3,
    minutos: 25,
    ingredientes: [
      { id: 'higado', cantidad: '500 g' },
      { id: 'cebolla', cantidad: '3 grandes' },
      { id: 'limon', cantidad: '1', alternativas: ['vinagre-manzana'] },
      { id: 'tomillo', cantidad: '1 cdita', alternativas: ['romero', 'oregano'] },
      { id: 'grasa-cerdo', cantidad: '2 cdas', alternativas: ['aceite-oliva', 'grasa-pato'] },
      { id: 'sal', cantidad: 'a gusto' },
      { id: 'perejil', cantidad: '2 cdas', opcional: true },
    ],
    pasos: [
      'Dejá el hígado en agua con el jugo de medio limón 20 minutos y secalo bien: le saca el amargor.',
      'Cortá las cebollas en pluma y cocinalas a fuego bajo con la grasa, 15 minutos, hasta que estén doradas y dulces.',
      'Subí el fuego, sumá el hígado en tiras y el tomillo. Cociná 3 minutos por lado: por dentro tiene que quedar apenas rosado.',
      'Salá al final (si salás antes se endurece) y terminá con limón y perejil.',
    ],
  },
  {
    id: 'fideos-zapallito-pesto',
    nombre: 'Fideos de zapallito con pesto de albahaca',
    emoji: '🌿',
    descripcion: 'Pesto sin queso ni piñones, que igual sale cremoso gracias a la palta.',
    momentos: ['almuerzo', 'cena'],
    porciones: 2,
    minutos: 20,
    ingredientes: [
      { id: 'zapallito', cantidad: '4', alternativas: ['zanahoria', 'pepino'], nota: 'cortados en tiras finas con pelapapas o espiralizador' },
      { id: 'albahaca', cantidad: '2 tazas', alternativas: ['rucula', 'perejil'] },
      { id: 'palta', cantidad: '1' },
      { id: 'ajo', cantidad: '1 diente' },
      { id: 'limon', cantidad: '1/2' },
      { id: 'aceite-oliva', cantidad: '4 cdas' },
      { id: 'sal', cantidad: 'a gusto' },
      { id: 'aceituna', cantidad: 'un puñado', opcional: true },
    ],
    pasos: [
      'Hacé tiras largas de zapallito con un pelapapas o espiralizador. Saladas y dejalas 10 minutos en un colador.',
      'Procesá albahaca, palta, ajo, limón, aceite y sal hasta que quede una crema.',
      'Secá bien las tiras de zapallito apretándolas con un repasador.',
      'Mezclá en frío con el pesto y serví enseguida, con aceitunas por encima.',
    ],
    nota: 'Si preferís tibio, saltá las tiras 2 minutos en sartén caliente y recién ahí mezclá el pesto.',
  },
  {
    id: 'bunuelos-acelga',
    nombre: 'Buñuelos de acelga',
    emoji: '🥬',
    descripcion: 'Para usar el atado de acelga antes de que se ponga feo. Salen de la sartén y no llegan a la mesa.',
    momentos: ['snack', 'cena', 'merienda'],
    porciones: 4,
    minutos: 30,
    ingredientes: [
      { id: 'acelga', cantidad: '1 atado', alternativas: ['espinaca', 'kale'] },
      { id: 'huevo', cantidad: '2' },
      { id: 'harina-mandioca', cantidad: '1/2 taza', alternativas: ['harina-sarraceno', 'harina-platano'] },
      { id: 'cebolla-verdeo', cantidad: '2', alternativas: ['cebolla', 'ciboulette'] },
      { id: 'ajo', cantidad: '1 diente' },
      { id: 'aceite-coco', cantidad: 'para freír', alternativas: ['grasa-cerdo', 'aceite-oliva'] },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Blanqueá la acelga 2 minutos en agua hirviendo, escurrila y apretala fuerte para sacarle toda el agua.',
      'Picala bien chica junto con la cebolla de verdeo y el ajo.',
      'Mezclá con los huevos, la harina y sal hasta formar una pasta espesa que se sostenga en la cuchara.',
      'Calentá 1 cm de aceite y echá cucharadas, aplastándolas un poco.',
      'Cociná 2 minutos de cada lado, hasta que estén dorados. Escurrilos sobre papel.',
    ],
  },
  {
    id: 'ensalada-tibia-remolacha',
    nombre: 'Ensalada tibia de remolacha, rúcula y pollo',
    emoji: '🥗',
    descripcion: 'Plato único que también funciona como vianda de oficina.',
    momentos: ['almuerzo'],
    porciones: 2,
    minutos: 45,
    ingredientes: [
      { id: 'remolacha', cantidad: '3', alternativas: ['zanahoria', 'batata'] },
      { id: 'pechuga-pollo', cantidad: '2', alternativas: ['muslo-pollo', 'pavo', 'salmon'] },
      { id: 'rucula', cantidad: '2 puñados', alternativas: ['berro', 'espinaca', 'radicheta'] },
      { id: 'cebolla-verdeo', cantidad: '2', opcional: true },
      { id: 'naranja', cantidad: '1', opcional: true, alternativas: ['mandarina'] },
      { id: 'aceite-oliva', cantidad: '3 cdas' },
      { id: 'vinagre-manzana', cantidad: '1 cda', alternativas: ['limon', 'vinagre-coco'] },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Envolvé las remolachas en papel de aluminio y horneálas a 200 °C durante 40 minutos, hasta que entre un cuchillo sin resistencia.',
      'Mientras tanto, cociná el pollo salado en sartén, 5 minutos de cada lado, y dejalo reposar antes de cortarlo.',
      'Pelá las remolachas tibias (la piel sale sola) y cortalas en gajos.',
      'Mezclá aceite, vinagre y sal para el aderezo.',
      'Armá con la rúcula de base, la remolacha tibia, el pollo en tiras y la naranja en gajos. Aderezá al servir.',
    ],
  },
  {
    id: 'sardinas-pepino-eneldo',
    nombre: 'Sardinas con ensalada de pepino y eneldo',
    emoji: '🥫',
    descripcion: 'Cinco minutos, cero cocción y una barbaridad de omega 3.',
    momentos: ['almuerzo', 'snack'],
    porciones: 2,
    minutos: 10,
    ingredientes: [
      { id: 'sardina', cantidad: '2 latas en aceite de oliva', alternativas: ['caballa', 'atun', 'anchoa'] },
      { id: 'pepino', cantidad: '2', alternativas: ['rabanito', 'hinojo', 'apio'] },
      { id: 'cebolla-verdeo', cantidad: '2', alternativas: ['ciboulette'] },
      { id: 'eneldo', cantidad: '2 cdas', alternativas: ['perejil', 'menta'] },
      { id: 'limon', cantidad: '1' },
      { id: 'aceite-oliva', cantidad: '2 cdas' },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Cortá el pepino en rodajas finas, salalo y dejalo escurrir 5 minutos.',
      'Mezclalo con la cebolla de verdeo en aros, el eneldo, el aceite y el jugo de limón.',
      'Serví las sardinas escurridas sobre la ensalada.',
    ],
  },
  {
    id: 'tarta-sarraceno-verduras',
    nombre: 'Tarta de sarraceno con verduras',
    emoji: '🥧',
    descripcion: 'Masa sin gluten que no se desarma. Rinde para la cena y la vianda del día siguiente.',
    momentos: ['almuerzo', 'cena'],
    porciones: 6,
    minutos: 70,
    ingredientes: [
      { id: 'harina-sarraceno', cantidad: '1 y 1/2 taza', alternativas: ['harina-mandioca'] },
      { id: 'huevo', cantidad: '4', nota: '1 para la masa, 3 para el relleno' },
      { id: 'aceite-oliva', cantidad: '5 cdas' },
      { id: 'agua', cantidad: '4 cdas' },
      { id: 'zapallito', cantidad: '2', alternativas: ['zapallo', 'brocoli', 'coliflor'] },
      { id: 'espinaca', cantidad: '2 puñados', alternativas: ['acelga', 'kale'] },
      { id: 'cebolla', cantidad: '1', alternativas: ['puerro', 'cebolla-verdeo'] },
      { id: 'ajo', cantidad: '2 dientes' },
      { id: 'leche-coco', cantidad: '1/2 taza', alternativas: ['crema-coco'] },
      { id: 'sal', cantidad: 'a gusto' },
      { id: 'oregano', cantidad: '1 cdita', opcional: true },
    ],
    pasos: [
      'Mezclá la harina de sarraceno con 1 huevo, 3 cdas de aceite, el agua y sal. Amasá hasta formar un bollo y dejalo descansar 15 minutos.',
      'Estirá la masa directamente sobre el molde, con los dedos: es quebradiza y no conviene estirarla con palo.',
      'Pinchala con un tenedor y horneála sola 12 minutos a 190 °C.',
      'Salteá cebolla, ajo y zapallito con el resto del aceite, 8 minutos. Sumá la espinaca y cociná hasta que se achique. Dejá entibiar.',
      'Batí los 3 huevos con la leche de coco, el orégano y sal, y mezclá con las verduras.',
      'Volcá sobre la masa prehorneada y horneá 30 minutos, hasta que el centro esté firme.',
    ],
  },

  // ══════════════════════ BÁSICOS ══════════════════════
  {
    id: 'caldo-huesos-base',
    nombre: 'Caldo de huesos',
    emoji: '🍵',
    descripcion: 'El básico del protocolo. Hacelo una vez y congelalo en porciones: mejora todo lo demás.',
    momentos: ['basico'],
    porciones: 8,
    minutos: 300,
    ingredientes: [
      { id: 'huesos', cantidad: '1,5 kg', nota: 'mejor con algo de carne y cartílago' },
      { id: 'zanahoria', cantidad: '2' },
      { id: 'apio', cantidad: '2 tallos', alternativas: ['hinojo', 'puerro'] },
      { id: 'cebolla', cantidad: '1, con cáscara' },
      { id: 'vinagre-manzana', cantidad: '2 cdas', nota: 'ayuda a extraer minerales del hueso' },
      { id: 'laurel', cantidad: '2 hojas' },
      { id: 'sal', cantidad: 'a gusto' },
      { id: 'agua', cantidad: '3 litros' },
    ],
    pasos: [
      'Si querés más sabor, dorá los huesos en el horno a 220 °C durante 30 minutos.',
      'Ponelos en la olla con el agua fría y el vinagre. Dejá reposar 30 minutos antes de prender el fuego.',
      'Llevá a hervor y sacá la espuma que se forma arriba.',
      'Sumá las verduras y el laurel. Bajá al mínimo y cociná 4 a 6 horas, apenas burbujeando.',
      'Colá, salá y dejá enfriar. La grasa sube y se retira fácil en frío.',
      'Guardá 5 días en heladera o congelá en porciones.',
    ],
  },
  {
    id: 'pate-higado',
    nombre: 'Paté de hígado',
    emoji: '🫙',
    descripcion: 'Para los que no quieren comer hígado. Untado en bastones de verdura, no se nota.',
    momentos: ['snack', 'basico'],
    porciones: 8,
    minutos: 30,
    ingredientes: [
      { id: 'higado', cantidad: '400 g', nota: 'de pollo, más suave' },
      { id: 'cebolla', cantidad: '2' },
      { id: 'ajo', cantidad: '3 dientes' },
      { id: 'grasa-cerdo', cantidad: '4 cdas', alternativas: ['aceite-coco', 'aceite-oliva', 'grasa-pato'] },
      { id: 'tomillo', cantidad: '1 cdita', alternativas: ['romero', 'salvia'] },
      { id: 'limon', cantidad: '1/2', alternativas: ['vinagre-manzana'] },
      { id: 'sal', cantidad: 'a gusto' },
    ],
    pasos: [
      'Rehogá las cebollas en la mitad de la grasa hasta que estén bien doradas, 15 minutos.',
      'Sumá el ajo y el hígado limpio y cociná 5 minutos: tiene que quedar apenas rosado adentro.',
      'Agregá el tomillo, el limón y sal.',
      'Procesá todo caliente con el resto de la grasa hasta que quede completamente liso.',
      'Pasalo a un frasco, alisá la superficie y refrigerá al menos 3 horas.',
    ],
    nota: 'Cubierto con una capa de grasa derretida dura 2 semanas en la heladera.',
  },
  {
    id: 'chips-batata',
    nombre: 'Chips de batata al horno',
    emoji: '🍟',
    descripcion: 'El snack para tener siempre. Lo importante es cortarlas finas y no amontonarlas.',
    momentos: ['snack', 'merienda'],
    porciones: 4,
    minutos: 35,
    ingredientes: [
      { id: 'batata', cantidad: '2 grandes', alternativas: ['mandioca', 'zapallo', 'remolacha', 'platano-verde'] },
      { id: 'aceite-oliva', cantidad: '3 cdas', alternativas: ['aceite-coco', 'aceite-palta'] },
      { id: 'sal', cantidad: 'a gusto' },
      { id: 'romero', cantidad: '1 cdita', opcional: true, alternativas: ['tomillo', 'ajo-polvo'] },
    ],
    pasos: [
      'Cortá las batatas en rodajas de 2 mm, con mandolina si tenés.',
      'Secalas bien con un repasador: la humedad es lo que las deja blandas.',
      'Mezclalas con aceite, sal y romero.',
      'Extendelas en una placa en una sola capa, sin que se toquen.',
      'Horneá a 180 °C durante 20 minutos, dalas vuelta y hacé 8 a 10 minutos más, vigilando: pasan de doradas a quemadas en un minuto.',
    ],
  },
  {
    id: 'crema-zanahoria-asada',
    nombre: 'Crema de zanahoria asada para untar',
    emoji: '🥕',
    descripcion: 'Lo que reemplaza al hummus. Dulce, ahumada y espesa, sin garbanzos ni sésamo.',
    momentos: ['snack', 'basico', 'merienda'],
    porciones: 6,
    minutos: 45,
    ingredientes: [
      { id: 'zanahoria', cantidad: '6', alternativas: ['zapallo', 'batata', 'remolacha'] },
      { id: 'ajo', cantidad: '4 dientes' },
      { id: 'aceite-oliva', cantidad: '5 cdas' },
      { id: 'limon', cantidad: '1' },
      { id: 'curcuma', cantidad: '1 cdita', opcional: true },
      { id: 'sal', cantidad: 'a gusto' },
      { id: 'perejil', cantidad: '2 cdas', opcional: true, alternativas: ['cilantro'] },
    ],
    pasos: [
      'Cortá las zanahorias en trozos y ponelas en una fuente con los ajos enteros con piel, aceite y sal.',
      'Asá a 200 °C durante 35 minutos, hasta que estén bien doradas en los bordes.',
      'Pelá los ajos asados y procesá todo con el jugo de limón, la cúrcuma y más aceite hasta lograr una crema.',
      'Serví con perejil y un hilo de aceite, con bastones de pepino, apio o zanahoria.',
    ],
  },

  // ══════════════════════ DULCES ══════════════════════
  {
    id: 'manzanas-horno-canela',
    nombre: 'Manzanas al horno con canela',
    emoji: '🍎',
    descripcion: 'El postre más simple del protocolo, y el que mejor le queda a una cena pesada.',
    momentos: ['dulce', 'merienda'],
    porciones: 4,
    minutos: 45,
    ingredientes: [
      { id: 'manzana', cantidad: '4', alternativas: ['pera'] },
      { id: 'canela', cantidad: '2 cditas' },
      { id: 'miel', cantidad: '2 cdas', opcional: true, alternativas: ['jarabe-arce', 'datil'] },
      { id: 'aceite-coco', cantidad: '2 cdas' },
      { id: 'coco-rallado', cantidad: '3 cdas', opcional: true },
      { id: 'agua', cantidad: '1/2 taza' },
    ],
    pasos: [
      'Sacales el centro a las manzanas con un descorazonador o un cuchillo fino, sin atravesarlas del todo.',
      'Ponelas en una fuente y rellená el hueco con aceite de coco, canela y miel.',
      'Volcá el agua en el fondo de la fuente para que no se sequen.',
      'Horneá a 180 °C durante 35 minutos, hasta que estén tiernas pero enteras.',
      'Serví tibias con el coco rallado por encima.',
    ],
  },
  {
    id: 'trufas-datil-coco',
    nombre: 'Trufas de dátil y coco',
    emoji: '🍡',
    descripcion: 'Se hacen en 10 minutos sin horno y resuelven el antojo de la tarde.',
    momentos: ['dulce', 'snack', 'merienda'],
    porciones: 12,
    minutos: 15,
    ingredientes: [
      { id: 'datil', cantidad: '15', alternativas: ['higo'], nota: 'si están secos, remojalos 10 minutos en agua caliente' },
      { id: 'coco-rallado', cantidad: '1 taza' },
      { id: 'aceite-coco', cantidad: '2 cdas' },
      { id: 'canela', cantidad: '1 cdita', opcional: true },
      { id: 'ralladura-limon', cantidad: '1 cdita', opcional: true, alternativas: ['jengibre'] },
      { id: 'sal', cantidad: '1 pizca' },
    ],
    pasos: [
      'Procesá los dátiles sin carozo hasta formar una pasta.',
      'Sumá 3/4 taza de coco rallado, el aceite de coco, la canela, la ralladura y la sal. Procesá hasta integrar.',
      'Armá bolitas con las manos apenas húmedas.',
      'Pasalas por el coco rallado restante y llevalas 30 minutos a la heladera.',
    ],
  },
  {
    id: 'mousse-mango-coco',
    nombre: 'Mousse de mango y coco',
    emoji: '🥭',
    descripcion: 'Tres ingredientes, textura de postre de restaurante.',
    momentos: ['dulce', 'merienda'],
    porciones: 4,
    minutos: 15,
    ingredientes: [
      { id: 'mango', cantidad: '2 maduros', alternativas: ['durazno', 'anana', 'banana'] },
      { id: 'crema-coco', cantidad: '400 ml', nota: 'la parte sólida de una lata de leche de coco fría', alternativas: ['leche-coco'] },
      { id: 'gelatina', cantidad: '1 sobre', opcional: true, nota: 'sin gelatina queda más suelto, tipo crema' },
      { id: 'lima', cantidad: '1', alternativas: ['limon'] },
      { id: 'miel', cantidad: '1 cda', opcional: true, alternativas: ['jarabe-arce'] },
    ],
    pasos: [
      'Dejá la lata de leche de coco en la heladera toda la noche y usá solo la parte sólida de arriba.',
      'Procesá el mango con el jugo de lima y la miel hasta que quede un puré liso.',
      'Si usás gelatina, hidratala en 3 cdas de agua fría y disolvela a baño maría. Mezclala con el puré de mango.',
      'Batí la crema de coco hasta que monte un poco e incorporala al mango con movimientos envolventes.',
      'Repartí en copas y refrigerá 3 horas.',
    ],
  },
  {
    id: 'budin-banana-sarraceno',
    nombre: 'Budín de banana y sarraceno',
    emoji: '🍌',
    descripcion: 'Húmedo por dentro, dorado por fuera. Aguanta cuatro días bien tapado.',
    momentos: ['dulce', 'desayuno', 'merienda'],
    porciones: 8,
    minutos: 60,
    ingredientes: [
      { id: 'banana', cantidad: '3 muy maduras' },
      { id: 'harina-sarraceno', cantidad: '1 y 1/2 taza', alternativas: ['harina-mandioca'], nota: 'con mandioca sale más compacto; sumá 1 huevo extra' },
      { id: 'huevo', cantidad: '3' },
      { id: 'aceite-coco', cantidad: '1/3 taza', alternativas: ['aceite-palta'] },
      { id: 'miel', cantidad: '3 cdas', opcional: true, alternativas: ['jarabe-arce'] },
      { id: 'canela', cantidad: '1 cdita' },
      { id: 'bicarbonato', cantidad: '1 cdita' },
      { id: 'vinagre-manzana', cantidad: '1 cdita', nota: 'activa el bicarbonato' },
      { id: 'sal', cantidad: '1 pizca' },
      { id: 'coco-rallado', cantidad: '2 cdas', opcional: true },
    ],
    pasos: [
      'Precalentá el horno a 175 °C y forrá un molde alargado con papel manteca.',
      'Pisá las bananas y mezclalas con los huevos, el aceite de coco derretido y la miel.',
      'Aparte, uní la harina, la canela, el bicarbonato y la sal.',
      'Integrá lo seco con lo húmedo y, al final, agregá el vinagre: la masa se va a esponjar un poco.',
      'Volcá en el molde, espolvoreá el coco rallado y horneá 45 minutos.',
      'Comprobá con un palillo: tiene que salir apenas húmedo. Dejalo enfriar en el molde antes de desmoldar, o se parte.',
    ],
  },
]

export const RECETA_POR_ID = new Map(RECETAS.map((r) => [r.id, r]))
